### PR TITLE
chore: update clarinet sdk to v2

### PR DESCRIPTION
**Pull request by hugocaillard**
# Description

- Update @hirosystems/clarinet-sdk and vitest-environment-clarinet to v2
  - The clarinet-sdk now relies on the deployment plan (default.simnet-plan.yaml) hence why there's this new file
- Also updated vite and vitest as part of this PR
  - Adapt the vitest config

### CODE REVIEW

**Review by moodmosaic — APPROVED** [review]
LGTM 👍 

We're currently using those also in https://github.com/stacks-network/stacks-core/pull/4550.

**Review by MarvinJanssen — APPROVED** [review]
Thanks @hugocaillard!

**Comment by hugocaillard** [comment]
Hey @MarvinJanssen 
Happy to, but I'm used to updating changelog on release, and this PR didn't update the version.
Do you want this PR to also bump the version?
Since you're recommending conventional commit, would you consider using something like
- [generate-changelog](https://www.npmjs.com/package/generate-changelog)
- [conventional-changelog-cli](https://www.npmjs.com/package/conventional-changelog-cli)

Definitely don't want to overkill of course, let's take the simplest solution

**Comment by MarvinJanssen** [comment]
I think it is necessary to publish the changes to npm. Perhaps @wileyj can chime in since he set it up.

**Comment by wileyj** [comment]
@hugocaillard @MarvinJanssen published (we have an issue to autopublish, low priority recently): https://www.npmjs.com/package/@stacks/clarunit

**Comment by hugocaillard** [comment]
Thanks @wileyj 
Can you push the version bump on github as well? thx

**Comment by wileyj** [comment]
meant to do that, thanks for reminder

**Comment by MarvinJanssen** [comment]
Thanks @wileyj!

**Pull request merged**
